### ISSUE TITLE
Feature: Chore functions only callable by controller

### ISSUE THREAD

**Issue by fabianschu** [PrimeDAO/balancer-v2-monorepo#16]
## User Story
**As** Index Finance, **I want** the two chore functions `reweighTokens` and `reindexTokens` to be only callable by the controller **so that** nobody can mess with the pool.

## Status Quo
- anybody can call these functions

## Acceptance Criteria
- [x] the functions can only be called by the controller
- [x] the  controller address is set in the constructor

## UPDATE
We decided to use the `owner` role to access certain functionalities instead of the controller role. The reason is that we have no possibility to add another address (controller) to the authentication process. Also, we would have otherwise two roles and addresses while only 1 is needed.

**Comment by Zitzak** [comment]
It was decided that we are going to use the `owner` passed during construction time as the controller. The reason for this is that we have no way to add another role to the authentication process inside Balancer V2
